### ISSUE TITLE
add encrypted data_bag or chef_vault docs

### ISSUE THREAD

**Issue by vinyar** [chef-cookbooks/supermarket-omnibus-cookbook#28]
Note: I understand that supermarket is still alpha

Bug: With github / source control underpinning and chef-server history retention, checking in a wrapper cookbook with secrets as node attributes is not the best practice.

Solution:
Add chef-vault or encrypted db support as an option

**Comment by robbkidd** [comment]
Good points. We'll add it to the triage.

**Comment by irvingpop** [comment]
hey @vinyar the recent refactor of this cookbook into a resource/provider ( https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/pull/22 ) was done with the intention of preventing the scenario you described.

Without trying to be opinionated about which secrets management tool is used,  what else would you want this cookbook to do?

**Comment by vinyar** [comment]
I was thinking of simply adding a supermarket['secret key'] or supermarket['vault_bag'] or something else. If attribute is defined use that to obtain a secret, if not proceed as is.

**Comment by agperson** [comment]
I quite like the move towards "bring your own secrets providers" approaches using resources.  Encrypted data bags and/or chef-vault are not the solution for everyone, but it would be impractical to also build in support for, say, Keywhiz, etcd, and Hashicorp Vault, not to mention whatever new secret management tool is announced tomorrow.

**Comment by nellshamrell** [comment]
Closing this for now, feel free to re-open if you feel further discussion is required.
