### ISSUE TITLE
Upload this cookbook version 1.1.0 to supermarket and override the existing one

### ISSUE THREAD

**Issue by iroller** [chef-cookbooks/supermarket-omnibus-cookbook#30]
There's an older version (older code) of this cookbook uploaded to https://supermarket.chef.io/cookbooks/supermarket-omnibus-cookbook having the same version "1.1.0". 

This is so confusing when you're assuming they're the same and trying to debug. Killed a couple hours before realizing I'm looking into code from github and using the one from supermarket which is different though has the same version tag.

Please save time to others and remove the current version from supermarket and upload the one from github.

**Comment by irvingpop** [comment]
done.
